services:
  db:
    image: mysql:5.7
    container_name: mysql_container
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${NAME_DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_backups:/backups
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost","-u", "${USER}", "-p${PASSWORD}"]
      interval: 10s
      timeout: 5s 
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mysql_phpmyadmin
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${USER}
      PMA_PASSWORD: ${PASSWORD}
volumes:
  mysql_data: {}
  mysql_backups: {}