events{
    worker_connections  1024;
}

http{
    upstream backend {
        server backend:3000;
    }

    upstream admin {
        server admin:4000;
    }
    server {
        listen 80;
        server_name localhost;

        location /backend/ {
            rewrite ^/backend/(.*)$ /$1 break;
            proxy_pass http://backend;
            # nagłówki 
            proxy_set_header Host $host; # przekazuje backendowu jaki adres wpisal user w przegladarce
            proxy_set_header X-Serice "BACKEND"; # prawdziwy adres ip użytkownika}
        }
        location /admin/ {
            rewrite ^/admin/(.*)$ /$1 break;
            proxy_pass http://admin;
            # nagłówki 
            proxy_set_header Host $host; # przekazuje backendowu jaki adres wpisal user w przegladarce
            proxy_set_header X-Serice "ADMIN"; # prawdziwy adres ip użytkownika}
        }
        location / {
            return 200 '{"message":"To jest api lub admin"}';
            add_header Content-Type application/json;
        }

    }
}