events{
    worker_connections  1024;
}

http{
    upstream backend {
        server backend:3000;
    }
    server {
        listen 80;

        location / {
            proxy_pass http://backend;
            # nagłówki 
            proxy_set_header Host $host; # przekazuje backendowu jaki adres wpisal user w przegladarce
            proxy_set_header X-Real-IP $remote_addr; # prawdziwy adres ip użytkownika
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # łańcuch adresów ip przez które przeszło zapytanie
        }
    }

    upstream backend {
        server backend:3000;
    }
    server {
        listen 80;

        location / {
            proxy_pass http://backend;
            # nagłówki 
            proxy_set_header Host $host; # przekazuje backendowu jaki adres wpisal user w przegladarce
            proxy_set_header X-Real-IP $remote_addr; # prawdziwy adres ip użytkownika
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # łańcuch adresów ip przez które przeszło zapytanie
        }
    }
}